### ISSUE TITLE
Stubs for imap_* functions are outdated on PHP 8.1

### ISSUE THREAD

**Issue by SMAtaurRahman** [phpstan/php-8-stubs#6]
Hi,
PHP 8.1 has changed imap_* function signatures to operate on `IMAP\Connection` class instead of `resource`.
This repo hasn't updated stubs for these functions yet.

As per my understanding, stubs are auto-generated. But if you need a PR, I am willing to do it.
Thanks.

**Comment by ondrejmirtes** [comment]
My idea is to somehow throw information from 8.1 into the mix, but it's not totally obvious how. PHPStan has to understand what's been changed in PHP 8.1 without a whole second copy of the stubs, that'd be wasteful. What I want to do is gonna be similar to `@since`, `@removed`, and `#[PhpStormStubsElementAvailable('8.0')]` that's used in https://github.com/jetbrains/phpstorm-stubs. Of course the extracting script should do all of this automatically on its own.

**Comment by ondrejmirtes** [comment]
FYI I want to work on this after I finish enums support.

**Comment by SMAtaurRahman** [comment]
> FYI I want to work on this after I finish enums support.

I'm currently trying to indulge myself into internals of static analyzers, so I'll be happy to invest some of my time if that's helpful to you.

**Comment by ondrejmirtes** [comment]
@SMAtaurRahman You can try to do some beginning of what I described here - https://github.com/phpstan/php-8-stubs/issues/6#issuecomment-992926200

E.g. compare the stubs between PHP 8.0 and PHP 8.1 and generate kind of a diff marked with attributes similarly to what's done here: https://github.com/JetBrains/phpstorm-stubs/blob/6146eb5541086ddef32fe29dd604da2d6839f3be/Core/Core_c.php#L293-L309

**Comment by SMAtaurRahman** [comment]
@ondrejmirtes I'm wondering why can't we just use phpstorm stubs then?

**Comment by ondrejmirtes** [comment]
All of these stubs are combined together for the best possible result. The stubs from php-src are the most corect so their information like native types always has the highest priority.

**Comment by SMAtaurRahman** [comment]
oh, okay.

**Comment by Hayajiro** [comment]
Hi @ondrejmirtes 

> FYI I want to work on this after I finish enums support.

Has there been any progress so far? I just now ran into this issue with the LDAP functions. I saw that you intended to work on this, so I wanted to check back with you before I have a look at it myself.

**Comment by ondrejmirtes** [comment]
@Hayajiro I haven't started yet ([It's not like I haven't been busy](https://github.com/phpstan/phpstan/releases)). I plan to do one more round of bugfixes and then work on PHPStan 1.5.0 in a week or two. You can try to start the work and send a small PR. (I prefer multiple iterations in small steps rather than one big change that's unlike to be successful.)

My idea is that `extract.php` should stay untouched and after running the current extract.php, the `PHP-8.1` branch of php-src should be checked out and a new `update.php` script should be executed that somehow projects the changes into the extracted stubs.

**Comment by Hayajiro** [comment]
Alright, I'll see if I can manage to get it into my work schedule. Thanks for the update!

**Comment by ondrejmirtes** [comment]
Here we go: https://github.com/phpstan/php-8-stubs/commit/861671519ccc7569311cc30b8e66b2ad6cf89a93 + https://github.com/phpstan/php-8-stubs/commit/c40d97077dc943d9c9b784ff3ad866ffff5419f9
